// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmowghyahqrsutrvzodp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtb3dnaHlhaHFyc3V0cnZ6b2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjQ2NjksImV4cCI6MjA2MTQ0MDY2OX0.AFakESpmDewBjIxJc9SsyKcSi9mbW8jNCSrvyacmyL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);